# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a4a96cb4b47cc15fa27f1ea22a28fea"
application_url = "https://accepted-good-maldives-leave.trycloudflare.com"
embedded = true
name = "vakx"
handle = "vakx-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_customers"

[auth]
redirect_urls = [
  "https://accepted-good-maldives-leave.trycloudflare.com/auth/callback",
  "https://accepted-good-maldives-leave.trycloudflare.com/auth/shopify/callback",
  "https://accepted-good-maldives-leave.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "vakx1.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
